export const LOAD_MORE_IMAGES_THRESHOLD = 5;

export const BASE_ELEVATION = 2;
export const DRAG_ELEVATION = 8;
export const END_POSITION_HORIZONTAL = 200;
export const END_THRESHOLD_HORIZONTAL = END_POSITION_HORIZONTAL / 2;
export const END_POSITION_VERTICAL = 150;
export const END_THRESHOLD_VERTICAL = END_POSITION_VERTICAL / 2;
